const actiontypes = {
    UPDATE_SHOP_COLLECTION: "UPDATE_SHOP_COLLECTION",
    START_FETCING :"START_FETCING",
    SUCCESS_UPDATE_COLLECTION: "SUCCESS_UPDATE_COLLECTION",
    FETCHING_FAILURE:"FETCHING_FAILURE"
}

export default actiontypes;